# Github action to build Docker image from main branch (tag: latest)
name: Build Docker image (latest)

on:
  workflow_dispatch:
  release:
    types:
      - published
#  schedule:
#    - cron: '42 3 * * 5'

jobs:
  bulid-latest-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (main)
        uses: actions/checkout@v2.3.4
        with:
          repository: 'buanet/pkitool.docker'
          ref: 'main'

      - name: Get and write version and date
        id: version
        run: |
          VERSION="$(cat .VERSION)"
          DATI="$(date --rfc-3339=seconds | sed 's/ /T/')"
          echo "This is the Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "This is the Buildnumber/Timestamp: $DATI"
          echo "dati=$DATI" >> $GITHUB_ENV
          # Set in Dockerfile
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${DATI}/$DATI/" ./Dockerfile > ./Dockerfile.tmp 
          mv -f ./Dockerfile.tmp ./Dockerfile

      - name: Set up manifest tool
        run: |
          wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
          chmod +x manifest-tool

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub (buanet)
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}

      - name: Build Docker image (amd64)
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            buanet/pkitool:${{ env.version }}-amd64,
            ghcr.io/buanet/pkitool:${{ env.version }}-amd64

      - name: Build Docker image (arm32v7)
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/arm/v7
          tags: |
            buanet/pkitool:${{ env.version }}-arm32v7,
            ghcr.io/buanet/pkitool:${{ env.version }}-arm32v7

      - name: Build Docker image (arm64v8)
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/arm64/v8
          tags: |
            buanet/pkitool:${{ env.version }}-arm64v8,
            ghcr.io/buanet/pkitool:${{ env.version }}-arm64v8

      - name: Create and push manifests (buanet)
        run: |
          sed -e "s/\${VERSION}/${{ env.version }}/g" -e "s/\${DOCKERTAG}/latest/g" ./manifest.yml > manifest_latest.yaml
          ./manifest-tool --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }} push from-spec manifest_latest.yaml
          sed -e "s/\${VERSION}/${{ env.version }}/g" -e "s/\${DOCKERTAG}/latest/g" ./manifest_ghcr.yml > manifest_ghcr_latest.yaml
          ./manifest-tool --username ${{ secrets.PACKAGES_USER }} --password ${{ secrets.PACKAGES_PASS }} push from-spec manifest_ghcr_latest.yaml
          sed -e "s/\${VERSION}/${{ env.version }}/g" -e "s/\${DOCKERTAG}/${{ env.version }}/g" ./manifest.yml > manifest_version.yaml
          ./manifest-tool --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }} push from-spec manifest_version.yaml
          sed -e "s/\${VERSION}/${{ env.version }}/g" -e "s/\${DOCKERTAG}/${{ env.version }}/g" ./manifest_ghcr.yml > manifest_ghcr_version.yaml
          ./manifest-tool --username ${{ secrets.PACKAGES_USER }} --password ${{ secrets.PACKAGES_PASS }} push from-spec manifest_ghcr_version.yaml

      - name: Delete untagged images from GitHub packages
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PACKAGES_PASS }}
          script: |
            const response = await github.request("GET /users/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions",
              { per_page: ${{ env.PER_PAGE }}
            });
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /user/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: buanet
          PACKAGE_NAME: pkitool
          PER_PAGE: 100